### ISSUE TITLE
Move back to `npm`

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/spraygun-react-ts#9]
It seems like `npm` is gaining favor again and `yarn` is losing support.

Should we think about moving this app back to assume only `npm` and not include `yarn`?

Let's discuss.  If we decide, I can probably put together a PR.

thoughts: @will-wow @alexwdaniel @mattbrictson @hannahhoward

**Comment by mattbrictson** [comment]
The tide does seem to be shifting back to `npm` but there is one major holdout: webpacker, which is bundled by default with all new Rails apps. My understanding is that `yarn` is hardcoded into the build system: https://github.com/rails/webpacker/issues/1746

If we anticipate that we will regularly be combining React and Rails via webpacker then it seems that using `yarn` would be the path of least resistance.

That said, I am not a fan of webpacker in general and would probably explore an [alternative](https://github.com/carbonfive/spraygun-react/blob/master/docs/how-to-use-with-rails-backend.md) for integrating React and Rails.

Just curious, what is the main argument for `npm` over `yarn`? It's bundled with Node so one less thing to install?

**Comment by bunnymatic** [comment]
It's been 2 years and we're still using `yarn`.  I feel like the main argument is, as you said, one less install.  But, it looks like `webpacker` is still using `yarn`.  I think it's general install time and lock management may still be a little better.  So maybe we close this until the tide *really* turns.

**Comment by mattbrictson** [comment]
In the last 2 years I have grown to appreciate webpacker. Considering webpacker is a standard part of Rails, I am probably going to follow their lead on yarn.

Also some more recent developments:

- `npm audit`, which was something that tempted me to switch to npm in the past, is now [considered a bad feature](https://overreacted.io/npm-audit-broken-by-design/), so I no longer have that fomo
- [npm supports `yarn.lock` files out of the box](https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson), so the cost of switching to npm (if you don't like what spraygun gives you), should be low

I'll close this issue for now.
